### ISSUE TITLE
Can't find gem on rubygems

### ISSUE THREAD

**Issue by jessieay** [ScrappyAcademy/rock_candy#10]
trying to use this gem and getting the following error when I bundle:

```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find gem 'rock_candy (>= 0) ruby' in the gems available on this machine.
```

**Comment by cupakromer** [comment]
Sorry about that. The gem never got enough dev time to get to a release point. You can point to the github repo in the gem file of you are still looking to use this.

**Comment by jessieay** [comment]
Cool, PR'd a change so that is clearer: https://github.com/ScrappyAcademy/rock_candy/pull/11

:rainbow:
